### ISSUE TITLE
'GoogleSignIn/GoogleSignIn.h' file not found

### ISSUE THREAD

**Issue by michaelcavallaro03** [bitrise-steplib/steps-xcode-archive#154]
Hi there,

Currently experiencing this issue only when running this step. I am able to archive and build in XCode(10.1).

I have tried several things including modifying header search paths, upgrading `react-native-firebase` and `react-native-google-signin` to latest packages. Like I said, everything builds successfully when I build locally.

Full error: 
```
In file included from /Users/vagrant/git/node_modules/react-native-google-signin/ios/RNGoogleSignin/RNGoogleSigninButtonManager.m:3:
RNGoogleSignin/RNGoogleSignin.h:8:9: fatal error: 'GoogleSignIn/GoogleSignIn.h' file not found
#import <GoogleSignIn/GoogleSignIn.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** ARCHIVE FAILED **
```

Please let me know if theres any other information I can provide!

**Comment by fehersanyi-bitrise** [comment]
Hello there, could you add a script step in which you run
`mdfind --name GoogleSignIn.h`
so we can check if it is actually there just in another path or not at all? 🙃

**Comment by michaelcavallaro03** [comment]
@fehersanyi-bitrise Thanks for getting back to me! I was able to run the command which gave the following output. 

```
/usr/local/Caskroom/android-sdk/4333796/extras/google/google_play_services/reference/com/google/android/gms/auth/api/signin/GoogleSignIn.html
```

So it appears that it can't find the file at all. I'm not quite sure how though?

**Comment by michaelcavallaro03** [comment]
Another update, the workflow ran successfully using Bitrise CLI. I even tried doing a fresh clone of repo and running the workflow which was successful.

**Comment by fehersanyi-bitrise** [comment]
Hy @michaelcavallaro03  from that output I think that header file is missing from the build somehow 🤔
maybe the dependency itself has some issue we don't know about yet.
maybe this thread could help https://github.com/react-native-community/react-native-google-signin/issues/343

**Comment by michaelcavallaro03** [comment]
Ended up committing my pods folder to ensure the header got there, working fine now! Thanks your leading me in the right direction!
